#pragma once

#include <cassert>
#include <map>
#include <memory>
#include <string>
#include "define.h"

//External forward declarations
class Dice;
class Var;

//Internal forward declarations
class CurrencySystem;
class Wallet;

class Currency
{
	public:
		std::string System = "";
		std::string Name = "";
		int SmallerAmount = 0;
		std::string Smaller = "";
		std::string Larger = "";

	private:

	//Parsing methods for Currency(std::string)
	void tryParseCurrencySystem(std::string* str, std::string fullstr);
	void tryParseName(std::string* str, std::string fullstr);
	void tryParseSmallerAmount(std::string* str, std::string fullstr);
	void tryParseSmaller(std::string* str, std::string fullstr);
	void tryParseLarger(std::string* str, std::string fullstr);

	public:
	Currency();
	Currency(const Currency& b);
	Currency(std::string str);
	Currency(std::string _Name, int _SmallerAmount, std::string _Smaller, std::string _Larger);
	Currency(std::string _System, std::string _Name, int _SmallerAmount, std::string _Smaller, std::string _Larger);

	explicit operator std::string() const;
	explicit operator bool() const;
	const char* c_str() const;
	Currency& operator = ([[maybe_unused]] const int b);
	Currency& operator = ([[maybe_unused]] const std::string b);
	Currency& operator = (const Var b);
	Currency& operator = ([[maybe_unused]] const Dice b);
	Currency& operator = ([[maybe_unused]] const Wallet b);
	Currency& operator = (const Currency b);
	Currency& operator = ([[maybe_unused]] const CurrencySystem b);
	Currency& operator += (const int b);
	Currency& operator += ([[maybe_unused]] const std::string b);
	Currency& operator += (const Var b);
	Currency& operator += ([[maybe_unused]] const Dice b);
	Wallet operator += (const Wallet b);
	Wallet operator += (const Currency b);
	Currency& operator += ([[maybe_unused]] const CurrencySystem b);
	Currency& operator -= (const int b);
	Currency& operator -= ([[maybe_unused]] const std::string b);
	Currency& operator -= (const Var b);
	Currency& operator -= ([[maybe_unused]] const Dice b);
	Currency& operator -= ([[maybe_unused]] const Wallet b);
	Currency& operator -= ([[maybe_unused]] const Currency b);
	Currency& operator -= ([[maybe_unused]] const CurrencySystem b);
	Wallet operator *= (const int b);
	Wallet operator *= ([[maybe_unused]] const std::string b);
	Wallet operator *= (const Var b);
	Currency& operator *= ([[maybe_unused]] const Dice b);
	Currency& operator *= ([[maybe_unused]] const Wallet b);
	Currency& operator *= ([[maybe_unused]] const Currency b);
	Currency& operator *= ([[maybe_unused]] const CurrencySystem b);
	Currency& operator /= ([[maybe_unused]] const int b);
	Currency& operator /= ([[maybe_unused]] const std::string b);
	Currency& operator /= (const Var b);
	Currency& operator /= ([[maybe_unused]] const Dice b);
	Currency& operator /= ([[maybe_unused]] const Wallet b);
	Currency& operator /= ([[maybe_unused]] const Currency b);
	Currency& operator /= ([[maybe_unused]] const CurrencySystem b);
	Currency& operator ^= ([[maybe_unused]] const int b);
	Currency& operator ^= ([[maybe_unused]] const std::string b);
	Currency& operator ^= (const Var b);
	Currency& operator ^= ([[maybe_unused]] const Dice b);
	Currency& operator ^= ([[maybe_unused]] const Wallet b);
	Currency& operator ^= ([[maybe_unused]] const Currency b);
	Currency& operator ^= ([[maybe_unused]] const CurrencySystem b);
	Currency& operator %= ([[maybe_unused]] const int b);
	Currency& operator %= ([[maybe_unused]] const std::string b);
	Currency& operator %= (const Var b);
	Currency& operator %= ([[maybe_unused]] const Dice b);
	Currency& operator %= ([[maybe_unused]] const Wallet b);
	Currency& operator %= ([[maybe_unused]] const Currency b);
	Currency& operator %= ([[maybe_unused]] const CurrencySystem b);
	Currency operator + (const int b);
	Currency operator + (const std::string b);
	Currency operator + (const Var b);
	Currency operator + (const Dice b);
	Wallet operator + (const Wallet b);
	Wallet operator + (const Currency b);
	Currency operator + (const CurrencySystem b);
	Currency operator - (const int b);
	Currency operator - (const std::string b);
	Currency operator - (const Var b);
	Currency operator - (const Dice b);
	Currency operator - (const Wallet b);
	Currency operator - (const Currency b);
	Currency operator - (const CurrencySystem b);
	Wallet operator * (const int b);
	Wallet operator * (const std::string b);
	Wallet operator * (const Var b);
	Currency operator * (const Dice b);
	Currency operator * (const Wallet b);
	Currency operator * (const Currency b);
	Currency operator * (const CurrencySystem b);
	Currency operator / (const int b);
	Currency operator / (const std::string b);
	Currency operator / (const Var b);
	Currency operator / (const Dice b);
	Currency operator / (const Wallet b);
	Currency operator / (const Currency b);
	Currency operator / (const CurrencySystem b);
	Currency operator ^ (const int b);
	Currency operator ^ (const std::string b);
	Currency operator ^ (const Var b);
	Currency operator ^ (const Dice b);
	Currency operator ^ (const Wallet b);
	Currency operator ^ (const Currency b);
	Currency operator ^ (const CurrencySystem b);
	Currency operator % (const int b);
	Currency operator % (const std::string b);
	Currency operator % (const Var b);
	Currency operator % (const Dice b);
	Currency operator % (const Wallet b);
	Currency operator % (const Currency b);
	Currency operator % (const CurrencySystem b);
	bool operator == ([[maybe_unused]] const int& b) const;
	bool operator == ([[maybe_unused]] const std::string& b) const;
	bool operator == (const Var& b) const;
	bool operator == ([[maybe_unused]] const Dice& b) const;
	bool operator == ([[maybe_unused]] const Wallet& b) const;
	bool operator == (const Currency& b) const;
	bool operator == ([[maybe_unused]] const CurrencySystem& b) const;
	bool operator < ([[maybe_unused]] const int& b) const;
	bool operator < ([[maybe_unused]] const std::string& b) const;
	bool operator < (const Var& b) const;
	bool operator < ([[maybe_unused]] const Dice& b) const;
	bool operator < ([[maybe_unused]] const Wallet& b) const;
	bool operator < (const Currency& b) const;
	bool operator < ([[maybe_unused]] const CurrencySystem& b) const;
	bool operator > ([[maybe_unused]] const int& b) const;
	bool operator > ([[maybe_unused]] const std::string& b) const;
	bool operator > (const Var& b) const;
	bool operator > ([[maybe_unused]] const Dice& b) const;
	bool operator > ([[maybe_unused]] const Wallet& b) const;
	bool operator > (const Currency& b) const;
	bool operator > ([[maybe_unused]] const CurrencySystem& b) const;
	bool operator <= (const int& b) const;
	bool operator <= (const std::string& b) const;
	bool operator <= (const Var& b) const;
	bool operator <= (const Dice& b) const;
	bool operator <= (const Wallet& b) const;
	bool operator <= (const Currency& b) const;
	bool operator <= (const CurrencySystem& b) const;
	bool operator >= (const int& b) const;
	bool operator >= (const std::string& b) const;
	bool operator >= (const Var& b) const;
	bool operator >= (const Dice& b) const;
	bool operator >= (const Wallet& b) const;
	bool operator >= (const Currency& b) const;
	bool operator >= (const CurrencySystem& b) const;
	bool operator != (const int& b) const;
	bool operator != (const std::string& b) const;
	bool operator != (const Var& b) const;
	bool operator != (const Dice& b) const;
	bool operator != (const Wallet& b) const;
	bool operator != (const Currency& b) const;
	bool operator != (const CurrencySystem& b) const;
	bool operator && (const int b);
	bool operator && (const std::string b);
	bool operator && (const Var b);
	bool operator && (const Dice b);
	bool operator && (const Wallet b);
	bool operator && (const Currency b);
	bool operator && (const CurrencySystem b);
	bool operator || (const int b);
	bool operator || (const std::string b);
	bool operator || (const Var b);
	bool operator || (const Dice b);
	bool operator || (const Wallet b);
	bool operator || (const Currency b);
	bool operator || (const CurrencySystem b);
	Currency& operator ++ (int);
	Currency& operator -- (int);
};
class CurrencySystem
{
	public:
		std::string Name = "";
		datamap<Currency> Denomination;
		Currency transaction = Currency();

	CurrencySystem();
	CurrencySystem(const CurrencySystem& b);
	CurrencySystem(std::string str);

	explicit operator std::string() const;
	explicit operator bool() const;
	const char* c_str() const;

	Currency& operator [] (const std::string b);
	CurrencySystem& operator = ([[maybe_unused]] const int b);
	CurrencySystem& operator = ([[maybe_unused]] const std::string b);
	CurrencySystem& operator = (const Var b);
	CurrencySystem& operator = ([[maybe_unused]] const Dice b);
	CurrencySystem& operator = ([[maybe_unused]] const Wallet b);
	CurrencySystem& operator = ([[maybe_unused]] const Currency b);
	CurrencySystem& operator = (const CurrencySystem b);
	CurrencySystem& operator += ([[maybe_unused]] const int b);
	CurrencySystem& operator += (const std::string b);
	CurrencySystem& operator += (const Var b);
	CurrencySystem& operator += ([[maybe_unused]] const Dice b);
	CurrencySystem& operator += ([[maybe_unused]] const Wallet b);
	CurrencySystem& operator += ([[maybe_unused]] const Currency b);
	CurrencySystem& operator += ([[maybe_unused]] const CurrencySystem b);
	CurrencySystem& operator -= ([[maybe_unused]] const int b);
	CurrencySystem& operator -= ([[maybe_unused]] const std::string b);
	CurrencySystem& operator -= (const Var b);
	CurrencySystem& operator -= ([[maybe_unused]] const Dice b);
	CurrencySystem& operator -= ([[maybe_unused]] const Wallet b);
	CurrencySystem& operator -= ([[maybe_unused]] const Currency b);
	CurrencySystem& operator -= ([[maybe_unused]] const CurrencySystem b);
	CurrencySystem& operator *= (const int b);
	CurrencySystem& operator *= ([[maybe_unused]] const std::string b);
	CurrencySystem& operator *= (const Var b);
	CurrencySystem& operator *= ([[maybe_unused]] const Dice b);
	CurrencySystem& operator *= ([[maybe_unused]] const Wallet b);
	CurrencySystem& operator *= ([[maybe_unused]] const Currency b);
	CurrencySystem& operator *= ([[maybe_unused]] const CurrencySystem b);
	CurrencySystem& operator /= ([[maybe_unused]] const int b);
	CurrencySystem& operator /= ([[maybe_unused]] const std::string b);
	CurrencySystem& operator /= (const Var b);
	CurrencySystem& operator /= ([[maybe_unused]] const Dice b);
	CurrencySystem& operator /= ([[maybe_unused]] const Wallet b);
	CurrencySystem& operator /= ([[maybe_unused]] const Currency b);
	CurrencySystem& operator /= ([[maybe_unused]] const CurrencySystem b);
	CurrencySystem& operator ^= ([[maybe_unused]] const int b);
	CurrencySystem& operator ^= ([[maybe_unused]] const std::string b);
	CurrencySystem& operator ^= (const Var b);
	CurrencySystem& operator ^= ([[maybe_unused]] const Dice b);
	CurrencySystem& operator ^= ([[maybe_unused]] const Wallet b);
	CurrencySystem& operator ^= ([[maybe_unused]] const Currency b);
	CurrencySystem& operator ^= ([[maybe_unused]] const CurrencySystem b);
	CurrencySystem& operator %= ([[maybe_unused]] const int b);
	CurrencySystem& operator %= ([[maybe_unused]] const std::string b);
	CurrencySystem& operator %= (const Var b);
	CurrencySystem& operator %= ([[maybe_unused]] const Dice b);
	CurrencySystem& operator %= ([[maybe_unused]] const Wallet b);
	CurrencySystem& operator %= ([[maybe_unused]] const Currency b);
	CurrencySystem& operator %= ([[maybe_unused]] const CurrencySystem b);
	CurrencySystem operator + (const int b);
	CurrencySystem operator + (const std::string b);
	CurrencySystem operator + (const Var b);
	CurrencySystem operator + (const Dice b);
	CurrencySystem operator + (const Wallet b);
	CurrencySystem operator + (const Currency b);
	CurrencySystem operator + (const CurrencySystem b);
	CurrencySystem operator - (const int b);
	CurrencySystem operator - (const std::string b);
	CurrencySystem operator - (const Var b);
	CurrencySystem operator - (const Dice b);
	CurrencySystem operator - (const Wallet b);
	CurrencySystem operator - (const Currency b);
	CurrencySystem operator - (const CurrencySystem b);
	CurrencySystem operator * (const int b);
	CurrencySystem operator * (const std::string b);
	CurrencySystem operator * (const Var b);
	CurrencySystem operator * (const Dice b);
	CurrencySystem operator * (const Wallet b);
	CurrencySystem operator * (const Currency b);
	CurrencySystem operator * (const CurrencySystem b);
	CurrencySystem operator / (const int b);
	CurrencySystem operator / (const std::string b);
	CurrencySystem operator / (const Var b);
	CurrencySystem operator / (const Dice b);
	CurrencySystem operator / (const Wallet b);
	CurrencySystem operator / (const Currency b);
	CurrencySystem operator / (const CurrencySystem b);
	CurrencySystem operator ^ (const int b);
	CurrencySystem operator ^ (const std::string b);
	CurrencySystem operator ^ (const Var b);
	CurrencySystem operator ^ (const Dice b);
	CurrencySystem operator ^ (const Wallet b);
	CurrencySystem operator ^ (const Currency b);
	CurrencySystem operator ^ (const CurrencySystem b);
	CurrencySystem operator % (const int b);
	CurrencySystem operator % (const std::string b);
	CurrencySystem operator % (const Var b);
	CurrencySystem operator % (const Dice b);
	CurrencySystem operator % (const Wallet b);
	CurrencySystem operator % (const Currency b);
	CurrencySystem operator % (const CurrencySystem b);
	bool operator == ([[maybe_unused]] const int& b) const;
	bool operator == ([[maybe_unused]] const std::string& b) const;
	bool operator == (const Var& b) const;
	bool operator == ([[maybe_unused]] const Dice& b) const;
	bool operator == ([[maybe_unused]] const Wallet& b) const;
	bool operator == ([[maybe_unused]] const Currency& b) const;
	bool operator == (const CurrencySystem& b) const;
	bool operator < ([[maybe_unused]] const int& b) const;
	bool operator < ([[maybe_unused]] const std::string& b) const;
	bool operator < (const Var& b) const;
	bool operator < ([[maybe_unused]] const Dice& b) const;
	bool operator < ([[maybe_unused]] const Wallet& b) const;
	bool operator < ([[maybe_unused]] const Currency& b) const;
	bool operator < ([[maybe_unused]] const CurrencySystem& b) const;
	bool operator > ([[maybe_unused]] const int& b) const;
	bool operator > ([[maybe_unused]] const std::string& b) const;
	bool operator > (const Var& b) const;
	bool operator > ([[maybe_unused]] const Dice& b) const;
	bool operator > ([[maybe_unused]] const Wallet& b) const;
	bool operator > ([[maybe_unused]] const Currency& b) const;
	bool operator > ([[maybe_unused]] const CurrencySystem& b) const;
	bool operator <= (const int& b) const;
	bool operator <= (const std::string& b) const;
	bool operator <= (const Var& b) const;
	bool operator <= (const Dice& b) const;
	bool operator <= (const Wallet& b) const;
	bool operator <= (const Currency& b) const;
	bool operator <= (const CurrencySystem& b) const;
	bool operator >= (const int& b) const;
	bool operator >= (const std::string& b) const;
	bool operator >= (const Var& b) const;
	bool operator >= (const Dice& b) const;
	bool operator >= (const Wallet& b) const;
	bool operator >= (const Currency& b) const;
	bool operator >= (const CurrencySystem& b) const;
	bool operator != (const int& b) const;
	bool operator != (const std::string& b) const;
	bool operator != (const Var& b) const;
	bool operator != (const Dice& b) const;
	bool operator != (const Wallet& b) const;
	bool operator != (const Currency& b) const;
	bool operator != (const CurrencySystem& b) const;
	bool operator && (const int b);
	bool operator && (const std::string b);
	bool operator && (const Var b);
	bool operator && (const Dice b);
	bool operator && (const Wallet b);
	bool operator && (const Currency b);
	bool operator && (const CurrencySystem b);
	bool operator || (const int b);
	bool operator || (const std::string b);
	bool operator || (const Var b);
	bool operator || (const Dice b);
	bool operator || (const Wallet b);
	bool operator || (const Currency b);
	bool operator || (const CurrencySystem b);
	CurrencySystem& operator ++ (int);
	CurrencySystem& operator -- (int);

	//Iterator type for the class
	using iterator = typename std::map<std::string, Currency>::const_iterator;

	//Beginning and end iterators.
	//So I can use "for(const auto& [key,val] : CurrencySystem){}"
	std::map<std::string, Currency>::const_iterator begin() const;
	std::map<std::string, Currency>::const_iterator end() const;

	void MakeChange(Currency c, Wallet* w);
	void TradeUp(Wallet* w);
	bool HasEquivalentTo(int Quantity, std::string Denomination);
};
typedef std::pair<Currency, int> money_t;
class Wallet
{
	public:
		std::map<Currency, int> Money;
		std::pair<Currency,int> transaction;

	bool HasEffectivelyAtLeast(int q, Currency c);
	unsigned int getEquivalentValueInLowestDenomination(CurrencySystem s);
	void print();
	void FloatQuantityToIntCurrency(Currency c, float q);
	bool containsCurrency(std::string currency_str);
	Currency getExistingCurrency(std::string currency_str);

	explicit operator std::string() const;
	explicit operator bool() const;
	const char* c_str() const;

	int& operator [] (const Currency b);

	//Iterator for the class
	using iterator = typename std::map<Currency, int>::const_iterator;

	//Beginning and end iterators. This is so I can use "for(const auto& [key,val] : Wallet){}"
	std::map<Currency, int>::const_iterator begin() const;
	std::map<Currency, int>::const_iterator end() const;

	Wallet();
	Wallet(const Wallet& b);
	Wallet(const money_t m);
	Wallet(std::string s);
	Wallet& operator = ([[maybe_unused]] const int b);
	Wallet& operator = ([[maybe_unused]] const std::string b);
	Wallet& operator = (const money_t b);
	Wallet& operator = (const Var b);
	Wallet& operator = ([[maybe_unused]] const Dice b);
	Wallet& operator = (const Wallet b);
	Wallet& operator = (const Currency b);
	Wallet& operator = ([[maybe_unused]] const CurrencySystem b);
	Wallet& operator += ([[maybe_unused]] const int b);
	Wallet& operator += ([[maybe_unused]] const std::string b);
	Wallet& operator += (const money_t b);
	Wallet& operator += (const Var b);
	Wallet& operator += ([[maybe_unused]] const Dice b);
	Wallet& operator += (const Wallet b);
	Wallet& operator += (const Currency b);
	Wallet& operator += ([[maybe_unused]] const CurrencySystem b);
	Wallet& operator -= ([[maybe_unused]] const int b);
	Wallet& operator -= ([[maybe_unused]] const std::string b);
	Wallet& operator -= (const money_t b);
	Wallet& operator -= (const Var b);
	Wallet& operator -= ([[maybe_unused]] const Dice b);
	Wallet& operator -= (const Wallet b);
	Wallet& operator -= (const Currency b);
	Wallet& operator -= ([[maybe_unused]] const CurrencySystem b);
	Wallet& operator *= (const int b);
	Wallet& operator *= ([[maybe_unused]] const std::string b);
	Wallet& operator *= ([[maybe_unused]] const money_t b);
	Wallet& operator *= (const Var b);
	Wallet& operator *= ([[maybe_unused]] const Dice b);
	Wallet& operator *= ([[maybe_unused]] const Wallet b);
	Wallet& operator *= ([[maybe_unused]] const Currency b);
	Wallet& operator *= ([[maybe_unused]] const CurrencySystem b);
	Wallet& operator /= (const int b);
	Wallet& operator /= ([[maybe_unused]] const std::string b);
	Wallet& operator /= ([[maybe_unused]] const money_t b);
	Wallet& operator /= (const Var b);
	Wallet& operator /= ([[maybe_unused]] const Dice b);
	Wallet& operator /= ([[maybe_unused]] const Wallet b);
	Wallet& operator /= ([[maybe_unused]] const Currency b);
	Wallet& operator /= ([[maybe_unused]] const CurrencySystem b);
	Wallet& operator ^= ([[maybe_unused]] const int b);
	Wallet& operator ^= ([[maybe_unused]] const std::string b);
	Wallet& operator ^= (const Var b);
	Wallet& operator ^= ([[maybe_unused]] const Dice b);
	Wallet& operator ^= ([[maybe_unused]] const Wallet b);
	Wallet& operator ^= ([[maybe_unused]] const Currency b);
	Wallet& operator ^= ([[maybe_unused]] const CurrencySystem b);
	Wallet& operator %= (const int b);
	Wallet& operator %= ([[maybe_unused]] const std::string b);
	Wallet& operator %= (const Var b);
	Wallet& operator %= ([[maybe_unused]] const Dice b);
	Wallet& operator %= ([[maybe_unused]] const Wallet b);
	Wallet& operator %= ([[maybe_unused]] const Currency b);
	Wallet& operator %= ([[maybe_unused]] const CurrencySystem b);
	Wallet operator + (const int b);
	Wallet operator + (const std::string b);
	Wallet operator + (const Var b);
	Wallet operator + (const Dice b);
	Wallet operator + (const Wallet b);
	Wallet operator + (const Currency b);
	Wallet operator + (const CurrencySystem b);
	Wallet operator - (const int b);
	Wallet operator - (const std::string b);
	Wallet operator - (const Var b);
	Wallet operator - (const Dice b);
	Wallet operator - (const Wallet b);
	Wallet operator - (const Currency b);
	Wallet operator - (const CurrencySystem b);
	Wallet operator * (const int b);
	Wallet operator * (const std::string b);
	Wallet operator * (const Var b);
	Wallet operator * (const Dice b);
	Wallet operator * (const Wallet b);
	Wallet operator * (const Currency b);
	Wallet operator * (const CurrencySystem b);
	Wallet operator / (const int b);
	Wallet operator / (const std::string b);
	Wallet operator / (const Var b);
	Wallet operator / (const Dice b);
	Wallet operator / (const Wallet b);
	Wallet operator / (const Currency b);
	Wallet operator / (const CurrencySystem b);
	Wallet operator ^ (const int b);
	Wallet operator ^ (const std::string b);
	Wallet operator ^ (const Var b);
	Wallet operator ^ (const Dice b);
	Wallet operator ^ (const Wallet b);
	Wallet operator ^ (const Currency b);
	Wallet operator ^ (const CurrencySystem b);
	Wallet operator % (const int b);
	Wallet operator % (const std::string b);
	Wallet operator % (const Var b);
	Wallet operator % (const Dice b);
	Wallet operator % (const Wallet b);
	Wallet operator % (const Currency b);
	Wallet operator % (const CurrencySystem b);
	bool operator == ([[maybe_unused]] const int& b) const;
	bool operator == ([[maybe_unused]] const std::string& b) const;
	bool operator == (const Var& b) const;
	bool operator == ([[maybe_unused]] const Dice& b) const;
	bool operator == (const Wallet& b) const;
	bool operator == (const Currency& b) const;
	bool operator == ([[maybe_unused]] const CurrencySystem& b) const;
	bool operator < ([[maybe_unused]] const int& b) const;
	bool operator < ([[maybe_unused]] const std::string& b) const;
	bool operator < (const Var& b) const;
	bool operator < ([[maybe_unused]] const Dice& b) const;
	bool operator < (const Wallet& b) const;
	bool operator < (const Currency& b) const;
	bool operator < ([[maybe_unused]] const CurrencySystem& b) const;
	bool operator > ([[maybe_unused]] const int& b) const;
	bool operator > ([[maybe_unused]] const std::string& b) const;
	bool operator > (const Var& b) const;
	bool operator > ([[maybe_unused]] const Dice& b) const;
	bool operator > (const Wallet& b) const;
	bool operator > (const Currency& b) const;
	bool operator > ([[maybe_unused]] const CurrencySystem& b) const;
	bool operator <= (const int& b) const;
	bool operator <= (const std::string& b) const;
	bool operator <= (const Var& b) const;
	bool operator <= (const Dice& b) const;
	bool operator <= (const Wallet& b) const;
	bool operator <= (const Currency& b) const;
	bool operator <= (const CurrencySystem& b) const;
	bool operator >= (const int& b) const;
	bool operator >= (const std::string& b) const;
	bool operator >= (const Var& b) const;
	bool operator >= (const Dice& b) const;
	bool operator >= (const Wallet& b) const;
	bool operator >= (const Currency& b) const;
	bool operator >= (const CurrencySystem& b) const;
	bool operator != (const int& b) const;
	bool operator != (const std::string& b) const;
	bool operator != (const Var& b) const;
	bool operator != (const Dice& b) const;
	bool operator != (const Wallet& b) const;
	bool operator != (const Currency& b) const;
	bool operator != (const CurrencySystem& b) const;
	bool operator && (const int b);
	bool operator && (const std::string b);
	bool operator && (const Var b);
	bool operator && (const Dice b);
	bool operator && (const Wallet b);
	bool operator && (const Currency b);
	bool operator && (const CurrencySystem b);
	bool operator || (const int b);
	bool operator || (const std::string b);
	bool operator || (const Var b);
	bool operator || (const Dice b);
	bool operator || (const Wallet b);
	bool operator || (const Currency b);
	bool operator || (const CurrencySystem b);
	Wallet& operator ++ ();
	Wallet& operator ++ (int);
	Wallet& operator -- ();
	Wallet& operator -- (int);

};
