#pragma once

#include <string>
#include "currency.h"
#include "dice.h"

class Var
{
	public:
		std::wstring Value = L"";

	Var(const Var& b);
	explicit operator std::wstring() const;
	explicit operator int() const;
	explicit operator bool() const;
	Var& operator = (const int b);
	Var& operator = (const std::wstring b);
	Var& operator = (const Var b);
	Var& operator = ([[maybe_unused]] const Dice b);
	Var& operator = ([[maybe_unused]] const Wallet b);
	Var& operator = ([[maybe_unused]] const Currency b);
	Var& operator += (const int b);
	Var& operator += (const std::wstring b);
	Var& operator += (const Var b);
	Var& operator += ([[maybe_unused]] const Dice b);
	Var& operator += ([[maybe_unused]] const Wallet b);
	Var& operator += ([[maybe_unused]] const Currency b);
	Var& operator -= (const int b);
	Var& operator -= ([[maybe_unused]] const std::wstring b);
	Var& operator -= (const Var b);
	Var& operator -= ([[maybe_unused]] const Dice b);
	Var& operator -= ([[maybe_unused]] const Wallet b);
	Var& operator -= ([[maybe_unused]] const Currency b);
	Var& operator *= (const int b);
	Var& operator *= ([[maybe_unused]] const std::wstring b);
	Var& operator *= (const Var b);
	Var& operator *= ([[maybe_unused]] const Dice b);
	Var& operator *= ([[maybe_unused]] const Wallet b);
	Var& operator *= ([[maybe_unused]] const Currency b);
	Var& operator /= (const int b);
	Var& operator /= ([[maybe_unused]] const std::wstring b);
	Var& operator /= (const Var b);
	Var& operator /= ([[maybe_unused]] const Dice b);
	Var& operator /= ([[maybe_unused]] const Wallet b);
	Var& operator /= ([[maybe_unused]] const Currency b);
	Var& operator ^= (const int b);
	Var& operator ^= ([[maybe_unused]] const std::wstring b);
	Var& operator ^= (const Var b);
	Var& operator ^= ([[maybe_unused]] const Dice b);
	Var& operator ^= ([[maybe_unused]] const Wallet b);
	Var& operator ^= ([[maybe_unused]] const Currency b);
	Var& operator %= (const int b);
	Var& operator %= ([[maybe_unused]] const std::wstring b);
	Var& operator %= (const Var b);
	Var& operator %= ([[maybe_unused]] const Dice b);
	Var& operator %= ([[maybe_unused]] const Wallet b);
	Var& operator %= ([[maybe_unused]] const Currency b);
	Var operator + (const int b);
	Var operator + (const std::wstring b);
	Var operator + (const Var b);
	Var operator + (const Dice b);
	Var operator + (const Wallet b);
	Var operator + (const Currency b);
	Var operator - (const int b);
	Var operator - (const std::wstring b);
	Var operator - (const Var b);
	Var operator - (const Dice b);
	Var operator - (const Wallet b);
	Var operator - (const Currency b);
	Var operator * (const int b);
	Var operator * (const std::wstring b);
	Var operator * (const Var b);
	Var operator * (const Dice b);
	Var operator * (const Wallet b);
	Var operator * (const Currency b);
	Var operator / (const int b);
	Var operator / (const std::wstring b);
	Var operator / (const Var b);
	Var operator / (const Dice b);
	Var operator / (const Wallet b);
	Var operator / (const Currency b);
	Var operator ^ (const int b);
	Var operator ^ (const std::wstring b);
	Var operator ^ (const Var b);
	Var operator ^ (const Dice b);
	Var operator ^ (const Wallet b);
	Var operator ^ (const Currency b);
	Var operator % (const int b);
	Var operator % (const std::wstring b);
	Var operator % (const Var b);
	Var operator % (const Dice b);
	Var operator % (const Wallet b);
	Var operator % (const Currency b);
	bool operator == (const int b);
	bool operator == (const std::wstring b);
	bool operator == (const Var b);
	bool operator == (const Dice b);
	bool operator == ([[maybe_unused]] const Wallet b);
	bool operator == ([[maybe_unused]] const Currency b);
	bool operator < (const int b);
	bool operator < (const std::wstring b);
	bool operator < (const Var b);
	bool operator < (const Dice b);
	bool operator < ([[maybe_unused]] const Wallet b);
	bool operator < ([[maybe_unused]] const Currency b);
	bool operator > (const int b);
	bool operator > (const std::wstring b);
	bool operator > (const Var b);
	bool operator > (const Dice b);
	bool operator > ([[maybe_unused]] const Wallet b);
	bool operator > ([[maybe_unused]] const Currency b);
	bool operator <= (const int b);
	bool operator <= (const std::wstring b);
	bool operator <= (const Var b);
	bool operator <= (const Dice b);
	bool operator <= (const Wallet b);
	bool operator <= (const Currency b);
	bool operator >= (const int b);
	bool operator >= (const std::wstring b);
	bool operator >= (const Var b);
	bool operator >= (const Dice b);
	bool operator >= (const Wallet b);
	bool operator >= (const Currency b);
	bool operator != (const int b);
	bool operator != (const std::wstring b);
	bool operator != (const Var b);
	bool operator != (const Dice b);
	bool operator != (const Wallet b);
	bool operator != (const Currency b);
	bool operator && (const int b);
	bool operator && (const std::wstring b);
	bool operator && (const Var b);
	bool operator && (const Dice b);
	bool operator && (const Wallet b);
	bool operator && (const Currency b);
	bool operator || (const int b);
	bool operator || (const std::wstring b);
	bool operator || (const Var b);
	bool operator || (const Dice b);
	bool operator || (const Wallet b);
	bool operator || (const Currency b);
	Var& operator ++ (int);
	Var& operator -- (int);

	Var();
	Var(std::wstring _value);
	Var(int _value);

	const char* c_str() const;
	bool isInt() const;
};
